# -*- coding: utf-8 -*-
"""fai_lab5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aVmyD6Fdz81Nrev9jJ_Rq4w7mP5n8oyN

Importing library
"""

from random import randint

"""Number guessing game"""

n = randint(1,10)
cnt = 0
while True:
  i = int(input("Guess the number between 1 and 10: "))
  cnt+=1
  if(i==n):
    print("You guessed it right in " + str(cnt) + " attempts")
    break

  else:
    print("Try again")